src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (
    AllAccountingView,
    AllCategoriesView,
    AllNeedsView,
    AllOpportunitiesView,
    CreateAccountingView,
    CreateCategoryView,
    CreateNeedView,
    CreateOpportunityView,
    DeleteAccountingView,
    DeleteCategoryView,
    DeleteNeedView,
    DeleteOpportunityView,
    RetrieveAccountingView,
    RetrieveCategoryView,
    RetrieveNeedView,
    RetrieveOpportunityView,
    UpdateAccountingView,
    UpdateCategoryView,
    UpdateNeedView,
    UpdateOpportunityView,
    UserViewSet,
)

app_name = "api"
routes = routers.DefaultRouter()
routes.register("users", UserViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="VolunteeringHub API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)

urlpatterns = [
    path("", include(routes.urls)),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("auth/", include("rest_framework.urls")),
    path("auth/", include("djoser.urls.jwt")),
    path("needs/", AllNeedsView.as_view(), name="all_needs"),
    path("needs/<int:pk>/", RetrieveNeedView.as_view(), name="need"),
    path("needs/create/", CreateNeedView.as_view(), name="create_need"),
    path("needs/update/<int:pk>/", UpdateNeedView.as_view(), name="update_need"),
    path("needs/delete/<int:pk>/", DeleteNeedView.as_view(), name="delete_need"),
    path("opportunities/", AllOpportunitiesView.as_view(), name="all_opportunities"),
    path("opportunities/<int:pk>/", RetrieveOpportunityView.as_view(), name="all_opportunities"),
    path("opportunities/create/", CreateOpportunityView.as_view(), name="create_opportunity"),
    path("opportunities/update/<int:pk>/", UpdateOpportunityView.as_view(), name="update_opportunity"),
    path("opportunities/delete/<int:pk>/", DeleteOpportunityView.as_view(), name="delete_opportunity"),
    path("categories/", AllCategoriesView.as_view(), name="all_categories"),
    path("categories/<int:pk>/", RetrieveCategoryView.as_view(), name="category"),
    path("categories/create/", CreateCategoryView.as_view(), name="create_category"),
    path("categories/update/<int:pk>/", UpdateCategoryView.as_view(), name="update_category"),
    path("categories/delete/<int:pk>/", DeleteCategoryView.as_view(), name="delete_category"),
    path("accounting/", AllAccountingView.as_view(), name="all_accounting"),
    path("accounting/<int:pk>/", RetrieveAccountingView.as_view(), name="accounting"),
    path("accounting/create/", CreateAccountingView.as_view(), name="create_accounting"),
    path("accounting/update/<int:pk>/", UpdateAccountingView.as_view(), name="update_accounting"),
    path("accounting/delete/<int:pk>/", DeleteAccountingView.as_view(), name="delete_accounting"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import NotFoundView, ServerErrorView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("api/", include("api.urls")),
    path("volunteering/", include("volunteering.urls")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()
handler500 = ServerErrorView.as_view()

src/core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from core.views import (
    IndexView,
    Login,
    Logout,
    Registration,
    ProfileView,
    NeededView,
    VolunteersView,
    ChangePassword,
    UpdateProfile,
)

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="core"),
    path("registration/", Registration.as_view(), name="registration"),
    path("change_password/", ChangePassword.as_view(), name="change_password"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("profile/<uuid:pk>", ProfileView.as_view(), name="profile"),
    path("profile/update/<uuid:pk>", UpdateProfile.as_view(), name="update_profile"),
    # path("profile/update/<uuid:pk>", UpdateProfile.as_view(), name="update_profile"),
    # path("update_photo/<uuid:pk>", UpdateProfilePhoto, name="UpdateProfilePhoto"),
    path("needed/", NeededView.as_view(), name="NeededView"),
    path("volunteers/", VolunteersView.as_view(), name="VolunteersView"),
]

urlpatterns += staticfiles_urlpatterns()

src/volunteering/urls.py
from django.urls import path

from volunteering.views import (
    CreateNeed,
    AllNeeds,
    AllOpportunities,
    CreateOpportunity,
    AllAccounting,
    CreateAccounting,
    user_generator,
    category_generator,
    accounting_generator,
    need_generator,
    opportunity_generator,
    NeedView,
    OpportunityView,
    AccountingView,
    UpdateNeed,
    UpdateAccounting,
    UpdateOpportunity,
    DeleteAccounting,
    DeleteNeed,
    DeleteOpportunity,
    CategoryView,
    AllCategories, HintNeed, CategoryNeeds, CategoryOpportunities,
)

app_name = "volunteering"

urlpatterns = [
    path("needs/", AllNeeds.as_view(), name="needs"),
    path("needs/<int:pk>", NeedView.as_view(), name="need"),
    path("needs/create/", CreateNeed.as_view(), name="create_need"),
    path("needs/update/<int:pk>", UpdateNeed.as_view(), name="update_need"),
    path("needs/delete/<int:pk>", DeleteNeed.as_view(), name="delete_need"),

    path("opportunities/", AllOpportunities.as_view(), name="opportunities"),
    path("opportunities/<int:pk>", OpportunityView.as_view(), name="opportunity"),
    path("opportunities/create", CreateOpportunity.as_view(), name="create_opportunity"),
    path("opportunities/update/<int:pk>", UpdateOpportunity.as_view(), name="update_opportunity"),
    path("opportunities/delete/<int:pk>", DeleteOpportunity.as_view(), name="delete_opportunity"),

    path("accounting/", AllAccounting.as_view(), name="accounting"),
    path("accounting/<int:pk>", AccountingView.as_view(), name="account"),
    path("accounting/create", CreateAccounting.as_view(), name="create_accounting"),
    path("accounting/update/<int:pk>", UpdateAccounting.as_view(), name="update_accounting"),
    path("accounting/delete/<int:pk>", DeleteAccounting.as_view(), name="delete_accounting"),

    path("categories/", AllCategories.as_view(), name="categories"),
    path("category/<str:name>", CategoryView.as_view(), name="category"),
    path("category/needs/<str:name>", CategoryNeeds.as_view(), name="category_needs"),
    path("category/opportunities/<str:name>", CategoryOpportunities.as_view(), name="category_opportunities"),

    path("needs/hint/<int:pk>", HintNeed.as_view(), name="hint_need"),

    path("generate/user", user_generator, name="user_generator"),
    path("generate/category", category_generator, name="category_generator"),
    path("generate/accounting", accounting_generator, name="accounting_generator"),
    path("generate/need", need_generator, name="need_generator"),
    path("generate/opportunity", opportunity_generator, name="opportunity_generator"),
]

src/volunteering/models.py
from django.db import models
from django.db.models import ImageField
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# Create your models here.


class Saver(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)


class Category(Saver):
    name = models.CharField(
        _("name"),
        max_length=256,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Opportunity(Saver):
    title = models.CharField(_("title"), max_length=100)
    description = models.TextField(_("description"), null=True, blank=True, default=None)
    photo = ImageField(_("photo"), upload_to="opportunity/", blank=True, null=True)
    category = models.ManyToManyField(
        to="volunteering.Category",
        related_name="opportunities",
    )
    city = models.CharField(_("city"), max_length=150, blank=True, null=True, default=None)
    author = models.ForeignKey(
        to="accounts.CustomUser", related_name="opportunity_author", on_delete=models.CASCADE, null=False, blank=False
    )
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Opportunities"


class Need(Saver):
    title = models.CharField(_("title"), max_length=100)
    description = models.TextField(_("description"), null=True, blank=True, default=None)
    photo = ImageField(_("photo"), upload_to="need/", blank=True, null=True)
    price = models.DecimalField(_("price"), decimal_places=2, max_digits=20, null=True, blank=True)
    donation = models.URLField(_("donation"), null=True, blank=True)
    accounting = models.ForeignKey(
        to="volunteering.Accounting", related_name="needs", on_delete=models.CASCADE, null=True, blank=True
    )
    category = models.ManyToManyField(
        to="volunteering.Category",
        related_name="needs",
        blank=True,
        null=True,
    )
    city = models.CharField(_("city"), max_length=150, blank=True, null=True, default=None)
    author = models.ForeignKey(
        to="accounts.CustomUser", related_name="need_author", on_delete=models.CASCADE, null=False, blank=False
    )
    is_satisfied = models.BooleanField(null=False, blank=False, default=False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.title) or ""

    def time_waiting(self):
        return timezone.now() - self.date_created


class Accounting(Saver):
    description = models.TextField(_("description"), null=True, blank=True, default=None)
    photo = ImageField(_("photo"), upload_to="accounting/", blank=True, null=True)
    author = models.ForeignKey(
        to="accounts.CustomUser", related_name="accounting_author", on_delete=models.CASCADE, null=False, blank=False
    )
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name_plural = "Accounting"

src/templates/volunteering/accounting_list.html
{% extends "index/index.html" %}
{% block content %}
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">Photo</th>
                    <th scope="col">Description</th>
                    <th scope="col">Author</th>
                    <th scope="col">Created</th>
                </tr>
                </thead>
                <tbody>
                {% if user.is_authenticated %}
                    <button type="button" class="btn btn-success"><a href="{% url "volunteering:create_accounting" %}">Create</a>
                    </button>
                {% endif %}
                {% for account in accounting %}
                    <tr data-href="{% url "volunteering:account" account.id %}">
                        <td>{% if account.photo %}<img src="{{ account.photo.url }}">{% endif %}</td>
                        <td>{{ account.description|truncatechars:50 }}</td>
                        <td><a href="{% url "core:profile" account.author.pk %}">{{ account.author.phone }}</a></td>
                        <td>{{ account.date_created }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>
                {% if page_obj.number > 3 %}
                    <a href="?page=1">1</a>
                    {% if page_obj.number > 4 %}
                        <span>...</span>
                    {% endif %}
                {% endif %}
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    <span>...</span>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
                <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
            {% endif %}
        </div>
    </section>
{% endblock content %}

src/templates/volunteering/category.html
{% extends "index/index.html" %}
{% block content %}
    <section class="contact-section bg-black">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card-body text-center">
                        <h1>{{ category.name }}</h1>
                        <hr style="size: A5">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            {% if needs %}
                <h2>Needs:</h2>
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Photo</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Price</th>
                        <th scope="col">Donation</th>
                        <th scope="col">City</th>
                        <th scope="col">Author</th>
                        {% if user.pk == user_page.pk %}
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for need in needs %}
                        <tr data-href="{% url "volunteering:need" need.pk %}">
                            <td>{% if need.photo %}<img src="{{ need.photo.url }}">{% endif %}</td>
                            <td>{{ need.title }}</td>
                            <td>{{ need.description|truncatechars:10 }}</td>
                            <td>{{ need.price }}</td>
                            <td>{{ need.donation }}</td>
                            <td>{{ need.city }}</td>
                            <td><a href="{% url "core:profile" need.author.pk %}">{{ need.author }}</a></td>
                            {% if user.pk == user_page.pk %}
                                <td><a href="{% url "volunteering:update_need" need.pk %}">Update</a></td>
                                <td><a href="{% url "volunteering:delete_need" need.pk %}">Delete</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            {% if opportunities %}
                <h2>Opportunities:</h2>
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Photo</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">City</th>
                        <th scope="col">Author</th>
                        {% if user.pk == user_page.pk %}
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for opportunity in opportunities %}
                        <tr data-href="{% url "volunteering:opportunity" opportunity.pk %}">
                            <td>{% if opportunity.photo %}
                                <img src="{{ opportunity.photo.url }}" height="100vh">{% endif %}</td>
                            <td>{{ opportunity.title }}</td>
                            <td>{{ opportunity.description|truncatechars:10 }}</td>
                            <td>{{ opportunity.city }}</td>
                            <td><a href="{% url "core:profile" opportunity.author.pk %}">{{ opportunity.author }}</a></td>
                            {% if user.pk == user_page.pk %}
                                <td><a href="{% url "volunteering:update_opportunity" opportunity.pk %}">Update</a>
                                </td>
                                <td><a href="{% url "volunteering:delete_opportunity" opportunity.pk %}">Delete</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/volunteering/category_needs.html
{% extends "index/index.html" %}
{% block content %}
    <section class="contact-section bg-black">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card-body text-center">
                        <h1>{{ category.name }}</h1>
                        <hr style="size: A5">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <h2>Needs:</h2>
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">Photo</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Price</th>
                    <th scope="col">Donation</th>
                    <th scope="col">City</th>
                    <th scope="col">Author</th>
                    {% if user.pk == user_page.pk %}
                        <th scope="col">Update</th>
                        <th scope="col">Delete</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for need in needs %}
                    <tr data-href="{% url "volunteering:need" need.pk %}">
                        <td>{% if need.photo %}<img src="{{ need.photo.url }}">{% endif %}</td>
                        <td>{{ need.title }}</td>
                        <td>{{ need.description|truncatechars:10 }}</td>
                        <td>{{ need.price }}</td>
                        <td>{{ need.donation }}</td>
                        <td>{{ need.city }}</td>
                        <td><a href="{% url "core:profile" need.author.pk %}">{{ need.author }}</a></td>
                        {% if user.pk == user_page.pk %}
                            <td><a href="{% url "volunteering:update_need" need.pk %}">Update</a></td>
                            <td><a href="{% url "volunteering:delete_need" need.pk %}">Delete</a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>
                {% if page_obj.number > 3 %}
                    <a href="?page=1">1</a>
                    {% if page_obj.number > 4 %}
                        <span>...</span>
                    {% endif %}
                {% endif %}
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    <span>...</span>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
                <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/volunteering/category_opportunities.html
{% extends "index/index.html" %}
{% block content %}
    <section class="contact-section bg-black">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card-body text-center">
                        <h1>{{ category.name }}</h1>
                        <hr style="size: A5">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            <h2>Opportunities:</h2>
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">Photo</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">City</th>
                    <th scope="col">Author</th>
                    {% if user.pk == user_page.pk %}
                        <th scope="col">Update</th>
                        <th scope="col">Delete</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for opportunity in opportunities %}
                    <tr data-href="{% url "volunteering:opportunity" opportunity.pk %}">
                        <td>{% if opportunity.photo %}
                            <img src="{{ opportunity.photo.url }}" height="100vh">{% endif %}</td>
                        <td>{{ opportunity.title }}</td>
                        <td>{{ opportunity.description|truncatechars:10 }}</td>
                        <td>{{ opportunity.city }}</td>
                        <td><a href="{% url "core:profile" opportunity.author.pk %}">{{ opportunity.author }}</a></td>
                        {% if user.pk == user_page.pk %}
                            <td><a href="{% url "volunteering:update_opportunity" opportunity.pk %}">Update</a>
                            </td>
                            <td><a href="{% url "volunteering:delete_opportunity" opportunity.pk %}">Delete</a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>
                {% if page_obj.number > 3 %}
                    <a href="?page=1">1</a>
                    {% if page_obj.number > 4 %}
                        <span>...</span>
                    {% endif %}
                {% endif %}
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    <span>...</span>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
                <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/volunteering/need_list.html
{% extends "index/index.html" %}
{% block content %}
<section class="about-section text-center" id="about">
    <div class="container px-4 px-lg-5">
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">Photo</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Price</th>
                <th scope="col">Donation</th>
                <th scope="col">Category</th>
                <th scope="col">City</th>
                <th scope="col">Author</th>
                <th scope="col">Created</th>
            </tr>
            </thead>
            <tbody>
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-success"><a href="{% url "volunteering:create_need" %}">Create</a>
                </button>
            {% endif %}
            {% for need in needs %}
                <tr data-href="{% url "volunteering:need" need.id %}">
                    <td>{% if need.photo %}<img src="{{ need.photo.url }}">{% endif %}</td>
                    <td>{{ need.title }}</td>
                    <td>{{ need.description|truncatechars:50 }}</td>
                    <td>{{ need.price }}</td>
                    <td>{{ need.donation }}</td>
                    <td>{% for category in need.category.all %}
                        <a href="{% url "volunteering:category" category %}">{{ category }}</a><br>{% endfor %}</td>
                    <td>{{ need.city }}</td>
                    <td><a href="{% url "core:profile" need.author.pk %}">{{ need.author }}</a></td>
                    <td>{{ need.date_created }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>
            {% if page_obj.number > 3 %}
                <a href="?page=1">1</a>
                {% if page_obj.number > 4 %}
                    <span>...</span>
                {% endif %}
            {% endif %}
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                <span>...</span>
                <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
            <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
        {% endif %}
    </div>
</section>
{% endblock content %}

src/templates/volunteering/opportunity_list.html
{% extends "index/index.html" %}
{% block content %}
<section class="about-section text-center" id="about">
    <div class="container px-4 px-lg-5">
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Photo</th>
                <th scope="col">Category</th>
                <th scope="col">City</th>
                <th scope="col">Author</th>
                <th scope="col">Created</th>
            </tr>
            </thead>
            <tbody>
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-success"><a href="{% url "volunteering:create_opportunity" %}">Create</a>
                </button>
            {% endif %}
            {% for opportunity in page_obj %}
                <tr data-href="{% url "volunteering:opportunity" opportunity.id %}">
                    <td>{% if opportunity.photo %}<img src="{{ opportunity.photo.url }}">{% endif %}</td>
                    <td>{{ opportunity.title }}</td>
                    <td>{{ opportunity.description|truncatechars:50 }}</td>
                    <td>{% for category in opportunity.category.all %}
                        <a href="{% url "volunteering:category" category %}">{{ category }}</a><br>{% endfor %}</td>
                    <td>{{ opportunity.city }}</td>
                    <td><a href="{% url "core:profile" opportunity.author.pk %}">{{ opportunity.author.phone }}</a></td>
                    <td>{{ opportunity.date_created }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>
            {% if page_obj.number > 3 %}
                <a href="?page=1">1</a>
                {% if page_obj.number > 4 %}
                    <span>...</span>
                {% endif %}
            {% endif %}
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                <span>...</span>
                <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
            <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
        {% endif %}
    </div>
</section>
{% endblock %}