src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (
    AllAccountingView,
    AllCategoriesView,
    AllNeedsView,
    AllOpportunitiesView,
    CreateAccountingView,
    CreateCategoryView,
    CreateNeedView,
    CreateOpportunityView,
    DeleteAccountingView,
    DeleteCategoryView,
    DeleteNeedView,
    DeleteOpportunityView,
    RetrieveAccountingView,
    RetrieveCategoryView,
    RetrieveNeedView,
    RetrieveOpportunityView,
    UpdateAccountingView,
    UpdateCategoryView,
    UpdateNeedView,
    UpdateOpportunityView,
    UserViewSet,
)

app_name = "api"
routes = routers.DefaultRouter()
routes.register("users", UserViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="VolunteeringHub API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[
        permissions.AllowAny,
    ],
)

urlpatterns = [
    path("", include(routes.urls)),
    path("docs/", schema_view.with_ui("swagger", cache_timeout=0), name="swagger_docs"),
    path("auth/", include("rest_framework.urls")),
    path("auth/", include("djoser.urls.jwt")),
    path("needs/", AllNeedsView.as_view(), name="all_needs"),
    path("needs/<int:pk>/", RetrieveNeedView.as_view(), name="need"),
    path("needs/create/", CreateNeedView.as_view(), name="create_need"),
    path("needs/update/<int:pk>/", UpdateNeedView.as_view(), name="update_need"),
    path("needs/delete/<int:pk>/", DeleteNeedView.as_view(), name="delete_need"),
    path("opportunities/", AllOpportunitiesView.as_view(), name="all_opportunities"),
    path("opportunities/<int:pk>/", RetrieveOpportunityView.as_view(), name="all_opportunities"),
    path("opportunities/create/", CreateOpportunityView.as_view(), name="create_opportunity"),
    path("opportunities/update/<int:pk>/", UpdateOpportunityView.as_view(), name="update_opportunity"),
    path("opportunities/delete/<int:pk>/", DeleteOpportunityView.as_view(), name="delete_opportunity"),
    path("categories/", AllCategoriesView.as_view(), name="all_categories"),
    path("categories/<int:pk>/", RetrieveCategoryView.as_view(), name="category"),
    path("categories/create/", CreateCategoryView.as_view(), name="create_category"),
    path("categories/update/<int:pk>/", UpdateCategoryView.as_view(), name="update_category"),
    path("categories/delete/<int:pk>/", DeleteCategoryView.as_view(), name="delete_category"),
    path("accounting/", AllAccountingView.as_view(), name="all_accounting"),
    path("accounting/<int:pk>/", RetrieveAccountingView.as_view(), name="accounting"),
    path("accounting/create/", CreateAccountingView.as_view(), name="create_accounting"),
    path("accounting/update/<int:pk>/", UpdateAccountingView.as_view(), name="update_accounting"),
    path("accounting/delete/<int:pk>/", DeleteAccountingView.as_view(), name="delete_accounting"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import NotFoundView, ServerErrorView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("api/", include("api.urls")),
    path("volunteering/", include("volunteering.urls")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = NotFoundView.as_view()
handler500 = ServerErrorView.as_view()

src/core/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from core.views import (
    IndexView,
    Login,
    Logout,
    Registration,
    ProfileView,
    NeededView,
    VolunteersView,
    ChangePassword,
    UpdateProfile,
)

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="core"),
    path("registration/", Registration.as_view(), name="registration"),
    path("change_password/", ChangePassword.as_view(), name="change_password"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("profile/<uuid:pk>", ProfileView.as_view(), name="profile"),
    path("profile/update/<uuid:pk>", UpdateProfile.as_view(), name="update_profile"),
    # path("profile/update/<uuid:pk>", UpdateProfile.as_view(), name="update_profile"),
    # path("update_photo/<uuid:pk>", UpdateProfilePhoto, name="UpdateProfilePhoto"),
    path("needed/", NeededView.as_view(), name="NeededView"),
    path("volunteers/", VolunteersView.as_view(), name="VolunteersView"),
]

urlpatterns += staticfiles_urlpatterns()

src/volunteering/urls.py
from django.urls import path

from volunteering.views import (
    CreateNeed,
    AllNeeds,
    AllOpportunities,
    CreateOpportunity,
    AllAccounting,
    CreateAccounting,
    user_generator,
    category_generator,
    accounting_generator,
    need_generator,
    opportunity_generator,
    NeedView,
    OpportunityView,
    AccountingView,
    UpdateNeed,
    UpdateAccounting,
    UpdateOpportunity,
    DeleteAccounting,
    DeleteNeed,
    DeleteOpportunity,
    CategoryView,
    AllCategories, HintNeed, CategoryNeeds, CategoryOpportunities,
)

app_name = "volunteering"

urlpatterns = [
    path("needs/", AllNeeds.as_view(), name="needs"),
    path("needs/<int:pk>", NeedView.as_view(), name="need"),
    path("needs/create/", CreateNeed.as_view(), name="create_need"),
    path("needs/update/<int:pk>", UpdateNeed.as_view(), name="update_need"),
    path("needs/delete/<int:pk>", DeleteNeed.as_view(), name="delete_need"),

    path("opportunities/", AllOpportunities.as_view(), name="opportunities"),
    path("opportunities/<int:pk>", OpportunityView.as_view(), name="opportunity"),
    path("opportunities/create", CreateOpportunity.as_view(), name="create_opportunity"),
    path("opportunities/update/<int:pk>", UpdateOpportunity.as_view(), name="update_opportunity"),
    path("opportunities/delete/<int:pk>", DeleteOpportunity.as_view(), name="delete_opportunity"),

    path("accounting/", AllAccounting.as_view(), name="accounting"),
    path("accounting/<int:pk>", AccountingView.as_view(), name="account"),
    path("accounting/create", CreateAccounting.as_view(), name="create_accounting"),
    path("accounting/update/<int:pk>", UpdateAccounting.as_view(), name="update_accounting"),
    path("accounting/delete/<int:pk>", DeleteAccounting.as_view(), name="delete_accounting"),

    path("categories/", AllCategories.as_view(), name="categories"),
    path("category/<str:name>", CategoryView.as_view(), name="category"),
    path("category/needs/<str:name>", CategoryNeeds.as_view(), name="category_needs"),
    path("category/opportunities/<str:name>", CategoryOpportunities.as_view(), name="category_opportunities"),

    path("needs/hint/<int:pk>", HintNeed.as_view(), name="hint_need"),

    path("generate/user", user_generator, name="user_generator"),
    path("generate/category", category_generator, name="category_generator"),
    path("generate/accounting", accounting_generator, name="accounting_generator"),
    path("generate/need", need_generator, name="need_generator"),
    path("generate/opportunity", opportunity_generator, name="opportunity_generator"),
]

src/accounts/models.py
from uuid import uuid4

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
from phonenumber_field.modelfields import PhoneNumberField

from accounts.managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    class UserTypeChoices(models.TextChoices):
        SINGLE_VOLUNTEER = "Single Volunteer", _("Single Volunteer")
        VOLUNTEERS_ORGANISATION = "Volunteers Organisation", _("Volunteers Organisation")
        CIVIL_PERSON = "Civil Person", _("Civil Person")
        MILITARY_PERSON = "Military Person", _("Military Person")

    type = models.CharField(
        max_length=23,
        choices=UserTypeChoices.choices,
    )
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid4,
        unique=True,
        db_index=True,
        editable=False,
    )
    email = models.EmailField(
        _("email address"),
        null=True,
        blank=True,
    )
    phone = PhoneNumberField(
        _("phone"),
        null=True,
        blank=True,
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. " "Unselect this instead of deleting accounts."
        ),
    )

    def __str__(self):
        if self.email:
            return str(self.email)
        else:
            return str(self.phone)

    USERNAME_FIELD = "email"

    objects = CustomUserManager()


class Profile(models.Model):
    user = models.OneToOneField(to="accounts.CustomUser", on_delete=models.CASCADE, blank=True, null=True)
    photo = models.ImageField(upload_to="profile/", blank=True, null=True, default="profile/profile_default.png")
    name = models.CharField(_("name"), max_length=150, blank=True, null=True, default=None)
    first_name = models.CharField(_("first name"), max_length=150, blank=True, null=True, default=None)
    last_name = models.CharField(_("last name"), max_length=150, blank=True, null=True, default=None)
    city = models.CharField(_("city"), max_length=150, blank=True, null=True, default=None)
    unit = models.CharField(_("unit"), max_length=250, blank=True, null=True, default=None)

    def __str__(self):
        if self.user.email:
            return str(self.user.email)
        else:
            return str(self.user.phone)

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField
from django.core.exceptions import ValidationError


class RegistrationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["type", "username", "phone", "email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields["type"].widget.attrs.update({"id": "type"})
        self.fields["username"].widget.attrs.update({"id": "username"})
        self.fields["phone"].widget.attrs.update({"id": "phone"})
        self.fields["email"].widget.attrs.update({"id": "email"})
        self.fields["password1"].widget.attrs.update({"id": "password1"})
        self.fields["password2"].widget.attrs.update({"id": "password2"})

    def clean(self):
        cleaned_data = super().clean()
        try:
            if (
                not bool(cleaned_data["email"])
                and not bool(cleaned_data["phone"])
                and not bool(cleaned_data["username"])
            ):
                raise ValidationError("Insert some data for registering you, please")

            elif not bool(cleaned_data["email"]) and not bool(cleaned_data["username"]):
                if get_user_model().objects.filter(phone=cleaned_data["phone"]).exists():
                    raise ValidationError("User with this phone number already exists.")

            elif not bool(cleaned_data["phone"]) and not bool(cleaned_data["username"]):
                if get_user_model().objects.filter(email=cleaned_data["email"]).exists():
                    raise ValidationError("User with this email already exists.")

            elif not bool(cleaned_data["email"]) and not bool(cleaned_data["phone"]):
                if get_user_model().objects.filter(email=cleaned_data["username"]).exists():
                    raise ValidationError("User with this username already exists.")

        except KeyError:
            raise ValidationError("Enter a valid info please")

        return cleaned_data


class CustomAuthenticationForm(AuthenticationForm):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    username/password logins.
    """

    username = UsernameField(label="Email or Phone number", widget=forms.TextInput(attrs={"autofocus": True}))

src/accounts/views.py
from django.shortcuts import render  # NOQA

# Create your views here.

src/templates/accounts/change_password.html
{% extends "index/index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="about-section text-center">
        <form enctype="multipart/form-data" method="post" style="width: 25em;
             align-content: center
             ; margin: auto;
    "> {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit">Submit</button>
        </form>
    </section>
{% endblock %}

src/templates/accounts/needed.html
{% extends "index/index.html" %}
{% block content %}
    <section class="about-section text-center">
        <div class="container px-4 px-lg-5">
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">Photo</th>
                    <th scope="col">Type</th>
                    <th scope="col">Contact</th>
                    <th scope="col">Name</th>
                    <th scope="col">City</th>
                </tr>
                </thead>
                <tbody>
                {% for needed_user in needed %}
                    <tr data-href="{% url "core:profile" needed_user.pk %}">
                        <td>{% if needed_user.profile.photo %}<img src="{{ needed_user.profile.photo.url }}">{% else %}No photo yet!{% endif %}</td>
                        <td>{{ needed_user.type }}</td>
                        <td><a href="{% url "core:profile" needed_user.pk %}">{{ needed_user }}</a></td>
                        <td>{{ needed_user.profile.first_name }} {{ needed_user.profile.last_name }}</td>
                        <td>{{ needed_user.profile.city }}</td>
                        <br>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>
                {% if page_obj.number > 3 %}
                    <a href="?page=1">1</a>
                    {% if page_obj.number > 4 %}
                        <span>...</span>
                    {% endif %}
                {% endif %}
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    <span>...</span>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
                <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
            {% endif %}
        </div>
    </section>
{% endblock content %}

src/templates/accounts/profile.html
{% extends "index/index.html" %}
{% load static %}
{% block content %}
    <section class="contact-section bg-black">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-3 mb-md-0"></div>
                <div class="col-md-4 mb-3 mb-md-0">
                    {% if user_page.email %}
                        <h1>{{ user_page.email }}</h1>
                    {% elif user_page.phone %}
                        <h1>{{ user_page.phone }}</h1>
                    {% endif %}
                    <hr style="size: A5">
                    <h3>{{ user_page.type }}</h3>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <div class="card-body text-center">
                        {% if user_page.profile.photo %}
                            <img src="{{ user_page.profile.photo.url }}">
                        {% else %}
                            <h2>Here could be your photo!</h2>
                        {% endif %}
                        <br>
                        {% if user_page.pk == user.pk %}
                            <button type="button" class="btn-dark">
                                <a href="{% url "core:update_profile" user_page.pk %}">Edit profile</a>
                            </button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="about-section text-center" id="about">
        <div class="container px-4 px-lg-5">
            {% if needs %}
                <h2>Needs:</h2>
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Photo</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Price</th>
                        <th scope="col">Donation</th>
                        <th scope="col">Category</th>
                        <th scope="col">City</th>
                        {% if user.pk == user_page.pk %}
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for need in needs %}
                        <tr data-href="{% url "volunteering:need" need.pk %}">
                            <td>{% if need.photo %}<img src="{{ need.photo.url }}">{% endif %}</td>
                            <td>{{ need.title }}</td>
                            <td>{{ need.description|truncatechars:10 }}</td>
                            <td>{{ need.price }}</td>
                            <td>{{ need.donation }}</td>
                            <td>{% for category in need.category.all %}<a href="{% url "volunteering:category" category %}">{{ category }}</a><br>{% endfor %}</td>
                            <td>{{ need.city }}</td>
                            {% if user.pk == user_page.pk %}
                                <td><a href="{% url "volunteering:update_need" need.pk %}">Update</a></td>
                                <td><a href="{% url "volunteering:delete_need" need.pk %}">Delete</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            {% if opportunities %}
                <h2>Opportunities:</h2>
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Photo</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Category</th>
                        <th scope="col">City</th>
                        {% if user.pk == user_page.pk %}
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for opportunity in opportunities %}
                        <tr data-href="{% url "volunteering:opportunity" opportunity.pk %}">
                            <td>{% if opportunity.photo %}
                                <img src="{{ opportunity.photo.url }}" height="100vh">{% endif %}</td>
                            <td>{{ opportunity.title }}</td>
                            <td>{{ opportunity.description|truncatechars:10 }}</td>
                            <td>{% for category in opportunity.category.all %}<a href="{% url "volunteering:category" category %}">{{ category }}</a><br>{% endfor %}</td>
                            <td>{{ opportunity.city }}</td>
                            {% if user.pk == user_page.pk %}
                                <td><a href="{% url "volunteering:update_opportunity" opportunity.pk %}">Update</a>
                                </td>
                                <td><a href="{% url "volunteering:delete_opportunity" opportunity.pk %}">Delete</a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            {% if accounting %}
                <h2>Accounting:</h2>
                <table class="table table-dark table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Photo</th>
                        <th scope="col">Description</th>
                        {% if user.pk == user_page.pk %}
                            <th scope="col">Update</th>
                            <th scope="col">Delete</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for account in accounting %}
                        <tr data-href="{% url "volunteering:account" account.pk %}">
                            <td>{% if account.photo %}
                                <img src="{{ account.photo.url }}" height="100vh">{% endif %}</td>
                            <td>{{ account.description|truncatechars:10 }}</td>
                            {% if user.pk == user_page.pk %}
                                <td><a href="{% url "volunteering:update_accounting" account.pk %}">Update</a></td>
                                <td><a href="{% url "volunteering:delete_accounting" account.pk %}">Delete</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/accounts/profile_form.html
{% extends "index/index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="about-section text-center">
        <form enctype="multipart/form-data" method="post" style="width: 25em;
             align-content: center
             ; margin: auto;"> {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" value="Submit">Submit</button>
        </form>
    </section>
    <br>
{% endblock content %}

src/templates/accounts/volunteers.html
{% extends "index/index.html" %}
{% block content %}
    <section class="about-section text-center">
        <div class="container px-4 px-lg-5">
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th scope="col">Photo</th>
                    <th scope="col">Type</th>
                    <th scope="col">Contact</th>
                    <th scope="col">Name</th>
                    <th scope="col">City</th>
                </tr>
                </thead>
                <tbody>
                {% for volunteer in volunteers %}
                    <tr data-href="{% url "core:profile" volunteer.pk %}">
                        <td>{% if volunteer.profile.photo %}<img src="{{ volunteer.profile.photo.url }}">{% else %}No photo yet!{% endif %}</td>
                        <td>{{ volunteer.type }}</td>
                        <td><a href="{% url "core:profile" volunteer.pk %}">{{ volunteer }}</a></td>
                        {% if volunteer.type == "Single Volunteer" %}
                            <td>{{ volunteer.profile.first_name }} {{ volunteer.profile.last_name }}</td>
                        {% else %}
                            <td>{{ volunteer.profile.name }}</td>
                        {% endif %}
                        <td>{{ volunteer.profile.city }}</td>
                        <br>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>
                {% if page_obj.number > 3 %}
                    <a href="?page=1">1</a>
                    {% if page_obj.number > 4 %}
                        <span>...</span>
                    {% endif %}
                {% endif %}
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                    <span>...</span>
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
                <a href="?page={{ page_obj.next_page_number }}">Next Page »</a>
            {% endif %}
        </div>
    </section>
{% endblock content %}